application:
  subdomain: memos
  public_path:
    - /api
  multi_instance: true
  ingress:
    - protocol: tcp
      port: 5230
      service: memos
  routes:
    - /=http://memos.cloud.lazycat.app.memos.lzcapp:5230
ext_config:
  disable_grpc_web_on_root: true
services:
  memos:
    # upstream: docker.io/neosmemo/memos:0.31.0@sha256:8596928c21551afc7d4e100051510bc134fd0caae51ad1d26cf899845d719321
    image: registry.lazycat.cloud/peter/neosmemo/memos:89101793b95ac298
    environment:
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0
      - MEMOS_PORT=5230
      - MEMOS_DRIVER=sqlite
      - MEMOS_DATA=/var/opt/memos
    binds:
      - /lzcapp/var/db/memos:/var/opt/memos
